// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Category struct {
	CategoryID int32
	Name       sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Comment struct {
	CommentID uuid.UUID
	UserID    uuid.UUID
	PostID    uuid.UUID
	Content   string
	Visible   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Favorite struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Group struct {
	GroupID     uuid.UUID
	Name        string
	Description string
	Photo       string
	Tag         string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type Like struct {
	UserID    uuid.UUID
	PostID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Notification struct {
	NotificationID uuid.UUID
	UserID         uuid.NullUUID
	SenderID       uuid.NullUUID
	Type           string
	Content        string
	Read           sql.NullBool
	CreatedAt      sql.NullTime
}

type Post struct {
	PostID     uuid.UUID
	UserID     uuid.UUID
	CategoryID sql.NullInt32
	Title      sql.NullString
	Content    string
	Photo      sql.NullString
	Video      sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type PostTag struct {
	PostID uuid.NullUUID
	TagID  sql.NullInt32
}

type Reply struct {
	ReplyID   uuid.UUID
	CommentID uuid.UUID
	UserID    uuid.UUID
	Content   string
	Visible   sql.NullBool
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Role struct {
	RoleID    uuid.UUID
	Name      string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Tag struct {
	TagID     int32
	Name      sql.NullString
	CreatedAt sql.NullTime
}

type User struct {
	UserID    uuid.UUID
	Username  string
	Email     string
	Password  string
	Avatar    sql.NullString
	Bio       sql.NullString
	Github    sql.NullString
	Linkedin  sql.NullString
	Website   sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type UserGroup struct {
	GroupID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
}

type UserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}

type View struct {
	ViewID    uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.NullUUID
	Count     sql.NullInt32
	CreatedAt sql.NullTime
}
